//recipepost constants
export const GET_RECIPEPOSTS = 'GET_RECIPEPOSTS';
export const GET_RECIPEPOSTS_LOAD = 'GET_RECIPEPOSTS_LOAD';
export const GET_RECIPEPOSTS_SUCCESS = 'GET_RECIPEPOSTS_SUCCESS';
export const GET_RECIPEPOSTS_FAIL = 'GET_RECIPEPOSTS_FAIL';

export const GET_RECIPEPOST_LOAD = 'GET_RECIPEPOST_LOAD';
export const GET_RECIPEPOST_SUCCESS = 'GET_RECIPEPOST_SUCCESS';
export const GET_RECIPEPOST_FAIL = 'GET_RECIPEPOST_FAIL';

export const GET_MYRECIPEPOSTS_LOAD = 'GET_MYRECIPEPOSTS_LOAD';
export const GET_MYRECIPEPOSTS_SUCCESS = 'GET_MYRECIPEPOSTS_SUCCESS';
export const GET_MYRECIPEPOSTS_FAIL = 'GET_MYRECIPEPOSTS_FAIL';

export const CREATE_RECIPEPOST = 'CREATE_RECIPEPOST';
export const CREATE_RECIPEPOST_LOAD = 'CREATE_RECIPEPOST_LOAD';
export const CREATE_RECIPEPOST_SUCCESS = 'CREATE_RECIPEPOST_SUCCESS';
export const CREATE_RECIPEPOST_FAIL = 'CREATE_RECIPEPOST_FAIL';

export const EDIT_RECIPEPOST = 'EDIT_RECIPEPOST';
export const EDIT_RECIPEPOST_LOAD = 'EDIT_RECIPEPOST_LOAD';
export const EDIT_RECIPEPOST_SUCCESS = 'EDIT_RECIPEPOST_SUCCESS';
export const EDIT_RECIPEPOST_FAIL = 'EDIT_RECIPEPOST_FAIL';

export const DELETE_RECIPEPOST = 'DELETE_RECIPEPOST';
export const DELETE_RECIPEPOST_LOAD = 'DELETE_RECIPEPOST_LOAD';
export const DELETE_RECIPEPOST_SUCCESS = 'DELETE_RECIPEPOST_SUCCESS';
export const DELETE_RECIPEPOST_FAIL = 'DELETE_RECIPEPOST_FAIL';

export const GET_REDDITPOSTS = 'GET_REDDITPOSTS';
export const GET_REDDITPOSTS_LOAD = 'GET_REDDITPOSTS_LOAD';
export const GET_REDDITPOSTS_SUCCESS = 'GET_REDDITPOSTS_SUCCESS';
export const GET_REDDITPOSTS_FAIL = 'GET_REDDITPOSTS_FAIL';

export const GET_REDDITPOST = 'GET_REDDITPOST';
export const GET_REDDITPOST_LOAD = 'GET_REDDITPOST_LOAD';
export const GET_REDDITPOST_SUCCESS = 'GET_REDDITPOST_SUCCESS';
export const GET_REDDITPOST_FAIL = 'GET_REDDITPOST_FAIL';

//comment constants
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_LOAD = 'CREATE_COMMENT_LOAD';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

//for removing new comments on component unmount
export const RESET_NEW_COMMENTS = 'RESET_NEW_COMMENTS';

//user constants
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_LOAD = 'REGISTER_USER_LOAD';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_LOAD = 'LOGIN_USER_LOAD';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT = 'LOGOUT';
